spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/econo_forest
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  kafka:
    listener:
      idle-partition-event-interval:

logging.level:
  org.hibernate.SQL: debug
#  org.springframework.transaction.interceptor : trace
#  org.hibernate.type: trace
#  org.hibernate.type.descriptor.sql: trace


# IDP 서버 요청
idp:
  api:
    uri: "http://168.131.30.127:8080/api/users/token"

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

