spring:
  datasource:
    url: jdbc:mysql://localhost:3306/econo_forest?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 12345pan
    driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  kafka:
    listener:
      idle-partition-event-interval:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug
#  org.springframework.transaction.interceptor : trace
#  org.hibernate.type: trace
#  org.hibernate.type.descriptor.sql: trace


# IDP 서버 요청
idp:
  api:
    uri: "http://168.131.30.127:8080/api/users"


server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

