INSERT INTO EAT_TOGATHER (EAT_TOGATHER_ID, EAT_TOGATHER_TITLE, EAT_TOGATHER_DATE_TIME, EAT_TOGATHER_LOCATION,
                          WRITER_ID)
VALUES (default, '테스트1', '2022-12-02 00:00:00', '후문', 1);


INSERT INTO EAT_TOGATHER_MEMBERS(EAT_TOGATHER_ID,EAT_TOGATHER_MEMBER,EAT_TOGATHER_MEMBER_IDX)
VALUES (1, 1, 0);