drop table if exists EAT_TOGATHER CASCADE;
drop table if exists EAT_TOGATHER_MEMBERS CASCADE;

create table EAT_TOGATHER
(
    EAT_TOGATHER_ID        bigint generated by default as identity,
    WRITER_ID              bigint,
    EAT_TOGATHER_DATE_TIME timestamp,
    EAT_TOGATHER_LOCATION  varchar(255),
    EAT_TOGATHER_TITLE    varchar(255),
    primary key (EAT_TOGATHER_ID)
);

create table EAT_TOGATHER_MEMBERS
(
    EAT_TOGATHER_ID         bigint  not null,
    EAT_TOGATHER_MEMBER     bigint,
    EAT_TOGATHER_MEMBER_IDX integer not null,
    primary key (EAT_TOGATHER_id, EAT_TOGATHER_MEMBER_IDX)
);

